### ISSUE TITLE
Error when running python3 TwOSINT.py twitter -n 5 -t & python3 TwOSINT.py twitter with the token added.

### ISSUE THREAD

**Issue by davidtkeane** [Zabrakk/TwOSINT#1]
pip3 and python3 are installed. 
I went through the steps you provided
I installed requirements.txt
I got my twitter bearer_token, made the file and added it there.
I ran all the commands listed in the install, and everything worked until I ran the python command

Traceback (most recent call last):
  File "/home/admin/TwOSINT/TwOSINT.py", line 15, in <module>
    logging.basicConfig(format='%(asctime)s %(name)s: %(message)s', level=logging.INFO,
  File "/usr/lib/python3.9/logging/__init__.py", line 1999, in basicConfig
    h = FileHandler(filename, mode,
  File "/usr/lib/python3.9/logging/__init__.py", line 1142, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin/TwOSINT/logs/log.txt'

I would love to solve this little problem if possible. 

Thank you.

**Comment by Zabrakk** [comment]
Alright, go ahead :thumbsup:
But keep in mind that I might modify your contribution at some point if I decide to continue working on this project.

**Comment by Zabrakk** [comment]
After waiting for some time, I decided to fix this issue myself.
See commit [bf07e0c](https://github.com/Zabrakk/TwOSINT/commit/bf07e0c1ce55a20360257bc43b74085f25e20479) for the fix.
